language: node_js

node_js:
  - 9

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: heroku
  app: june-practice-12
  api_key:
    secure: $HEROKU_KEY

