language: node_js

node_js:
  - 9

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

script:
  - yarn build
  - rm build/static/js/*.js.map
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY

  app: june-practice-12
